"""empty message

Revision ID: 919ea8c3827f
Revises: cb987e2d5692
Create Date: 2023-02-21 10:25:11.571815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919ea8c3827f'
down_revision = 'cb987e2d5692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('transactions_btree_index', table_name='transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('transactions_btree_index', 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###
