"""empty message

Revision ID: 87923eb530fe
Revises: 633f83a40947
Create Date: 2023-02-14 16:34:44.701960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87923eb530fe'
down_revision = '633f83a40947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
