"""empty message

Revision ID: 847d069e5c8d
Revises: da371afd69e5
Create Date: 2023-02-12 15:41:19.028462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847d069e5c8d'
down_revision = 'da371afd69e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subcatname', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategories')
    # ### end Alembic commands ###
