"""empty message

Revision ID: 633f83a40947
Revises: cf4b269bf1e2
Create Date: 2023-02-14 16:31:07.196419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633f83a40947'
down_revision = 'cf4b269bf1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'account_id_id')
    )
    op.add_column('accounts', sa.Column('acctname', sa.String(), nullable=False))
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'acctname')
    op.drop_table('users_accounts')
    # ### end Alembic commands ###
