"""empty message

Revision ID: c835a876301f
Revises: 088213edeea3
Create Date: 2023-02-21 14:16:22.459830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c835a876301f'
down_revision = '088213edeea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_subcategories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_subcategories',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name='users_subcategories_subcategory_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_subcategories_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'subcategory_id', name='users_subcategories_pkey')
    )
    # ### end Alembic commands ###
