"""empty message

Revision ID: 988d2f63530f
Revises: 87923eb530fe
Create Date: 2023-02-14 16:52:23.575475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988d2f63530f'
down_revision = '87923eb530fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_accounts')
    op.drop_table('accounts')
    op.add_column('transactions', sa.Column('description', sa.String(length=128), nullable=True))
    op.drop_constraint('transactions_payee_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_payer_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'payee_id')
    op.drop_column('transactions', 'payer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('payee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('transactions_payer_id_fkey', 'transactions', 'accounts', ['payer_id'], ['id'])
    op.create_foreign_key('transactions_payee_id_fkey', 'transactions', 'accounts', ['payee_id'], ['id'])
    op.drop_column('transactions', 'description')
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('accounts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('acctname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='accounts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users_accounts',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id_id'], ['accounts.id'], name='users_accounts_account_id_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_accounts_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'account_id_id', name='users_accounts_pkey')
    )
    # ### end Alembic commands ###
