"""empty message

Revision ID: 088213edeea3
Revises: 919ea8c3827f
Create Date: 2023-02-21 14:15:36.040813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088213edeea3'
down_revision = '919ea8c3827f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_categories',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='users_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_categories_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name='users_categories_pkey')
    )
    # ### end Alembic commands ###
